RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe

  0%|          | 0/110 [00:00<?, ?it/s][A
  1%|          | 1/110 [12:58<23:34:45, 778.77s/it][A
  2%|▏         | 2/110 [12:59<9:37:43, 320.96s/it] [A
  7%|▋         | 8/110 [13:11<1:33:10, 54.80s/it] [A
 11%|█         | 12/110 [13:11<49:53, 30.55s/it] [A
 11%|█         | 12/110 [13:21<49:53, 30.55s/it][A
 15%|█▍        | 16/110 [13:24<31:17, 19.97s/it][A
 66%|██████▋   | 73/110 [20:36<05:31,  8.97s/it][A
 67%|██████▋   | 74/110 [20:37<05:17,  8.81s/it][A
 70%|███████   | 77/110 [20:41<04:29,  8.16s/it][A
 71%|███████   | 78/110 [20:41<04:11,  7.86s/it][A
 74%|███████▎  | 81/110 [20:43<03:17,  6.81s/it][A
 75%|███████▍  | 82/110 [20:45<03:02,  6.53s/it][A
 75%|███████▌  | 83/110 [20:47<02:43,  6.07s/it][A
 76%|███████▋  | 84/110 [20:49<02:26,  5.64s/it][A
 80%|████████  | 88/110 [20:51<01:22,  3.74s/it][A
 83%|████████▎ | 91/110 [20:51<00:50,  2.68s/it][A
 86%|████████▋ | 95/110 [20:51<00:26,  1.74s/it][A
 90%|█████████ | 99/110 [20:51<00:12,  1.16s/it][A100%|██████████| 110/110 [20:51<00:00, 11.38s/it]

  0%|          | 0/110 [00:00<?, ?it/s][A
  1%|          | 1/110 [13:45<24:59:03, 825.17s/it][A
  2%|▏         | 2/110 [13:51<10:18:39, 343.70s/it][A
  4%|▎         | 4/110 [13:56<3:48:54, 129.57s/it] [A
 15%|█▍        | 16/110 [13:57<31:58, 20.41s/it]  [A
 42%|████▏     | 46/110 [13:59<05:28,  5.13s/it][A
 66%|██████▋   | 73/110 [21:36<06:44, 10.94s/it][A
 67%|██████▋   | 74/110 [21:43<06:30, 10.84s/it][A
 69%|██████▉   | 76/110 [21:44<05:44, 10.13s/it][A
 70%|███████   | 77/110 [21:45<05:19,  9.69s/it][A
 86%|████████▋ | 95/110 [21:45<01:06,  4.45s/it][A
 91%|█████████ | 100/110 [21:45<00:36,  3.67s/it][A
 95%|█████████▍| 104/110 [21:45<00:18,  3.06s/it][A100%|██████████| 110/110 [21:45<00:00, 11.87s/it]

  0%|          | 0/110 [00:00<?, ?it/s][A
  1%|          | 1/110 [13:54<25:15:50, 834.40s/it][A
 66%|██████▋   | 73/110 [21:01<08:34, 13.91s/it]   [A
 77%|███████▋  | 85/110 [21:05<04:42, 11.31s/it][A
 93%|█████████▎| 102/110 [21:05<01:05,  8.17s/it][A100%|██████████| 110/110 [21:05<00:00, 11.51s/it]

  0%|          | 0/110 [00:00<?, ?it/s][A
  1%|          | 1/110 [13:07<23:50:34, 787.47s/it][A
 17%|█▋        | 19/110 [13:10<44:57, 29.64s/it]   [A
 23%|██▎       | 25/110 [13:17<29:18, 20.68s/it][A
 66%|██████▋   | 73/110 [19:06<06:17, 10.20s/it][A
 67%|██████▋   | 74/110 [19:28<06:16, 10.46s/it][A
 68%|██████▊   | 75/110 [20:01<06:31, 11.19s/it][A
 70%|███████   | 77/110 [20:03<05:41, 10.34s/it][A
 78%|███████▊  | 86/110 [20:06<02:44,  6.86s/it][A
 85%|████████▍ | 93/110 [20:06<01:24,  4.97s/it][A100%|██████████| 110/110 [20:06<00:00, 10.97s/it]

  0%|          | 0/110 [00:00<?, ?it/s][A
  1%|          | 1/110 [13:41<24:52:12, 821.40s/it][A
 40%|████      | 44/110 [13:59<14:55, 13.56s/it]   [A
 66%|██████▋   | 73/110 [20:45<08:30, 13.78s/it][A
 74%|███████▎  | 81/110 [20:47<05:36, 11.59s/it][A
 79%|███████▉  | 87/110 [20:47<03:47,  9.89s/it][A
 84%|████████▎ | 92/110 [20:47<02:31,  8.42s/it][A100%|██████████| 110/110 [20:47<00:00, 11.34s/it]
Exception ignored in: <function Pool.__del__ at 0x2aae6700c4c0>
Traceback (most recent call last):
  File "/home/n9455647/.conda/envs/conda_test/lib/python3.8/multiprocessing/pool.py", line 268, in __del__
  File "/home/n9455647/.conda/envs/conda_test/lib/python3.8/multiprocessing/queues.py", line 362, in put
AttributeError: 'NoneType' object has no attribute 'dumps'
