RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
  0%|          | 0/1 [00:00<?, ?it/s]
  0%|          | 0/112 [00:00<?, ?it/s][A
  1%|          | 1/112 [14:03<26:00:07, 843.31s/it][A
  4%|▍         | 5/112 [14:10<3:46:42, 127.13s/it] [A
  5%|▌         | 6/112 [16:08<3:40:46, 124.97s/it][A
  6%|▋         | 7/112 [19:00<3:59:17, 136.73s/it][A
 50%|█████     | 56/112 [19:03<06:57,  7.46s/it]  [A
 69%|██████▉   | 77/112 [22:32<04:52,  8.37s/it][A
 70%|██████▉   | 78/112 [22:56<04:57,  8.75s/it][A
 71%|███████   | 79/112 [23:37<05:24,  9.84s/it][A
 71%|███████▏  | 80/112 [23:39<05:02,  9.47s/it][A
 74%|███████▍  | 83/112 [24:00<04:23,  9.09s/it][A
 79%|███████▊  | 88/112 [24:25<03:10,  7.92s/it][A
 79%|███████▉  | 89/112 [24:29<02:55,  7.61s/it][A
 81%|████████▏ | 91/112 [24:32<02:17,  6.53s/it][A
 88%|████████▊ | 99/112 [24:34<00:44,  3.42s/it][A
 96%|█████████▋| 108/112 [24:44<00:09,  2.39s/it][A100%|██████████| 112/112 [24:44<00:00, 13.25s/it]
100%|██████████| 1/1 [24:56<00:00, 1496.79s/it]100%|██████████| 1/1 [24:56<00:00, 1496.79s/it]
Exception ignored in: <function Pool.__del__ at 0x2b025ef7c4c0>
Traceback (most recent call last):
  File "/home/n9455647/.conda/envs/conda_test/lib/python3.8/multiprocessing/pool.py", line 268, in __del__
  File "/home/n9455647/.conda/envs/conda_test/lib/python3.8/multiprocessing/queues.py", line 362, in put
AttributeError: 'NoneType' object has no attribute 'dumps'
