RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
  0%|          | 0/9 [00:00<?, ?it/s]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [09:27<1:06:15, 567.95s/it][A
 38%|███▊      | 3/8 [09:28<12:16, 147.36s/it]  [A
 50%|█████     | 4/8 [09:29<06:26, 96.64s/it] [A
 62%|██████▎   | 5/8 [09:29<03:14, 64.75s/it][A100%|██████████| 8/8 [09:29<00:00, 71.16s/it]
 11%|█         | 1/9 [12:36<1:40:48, 756.02s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [09:22<1:05:38, 562.61s/it][A
 25%|██▌       | 2/8 [09:24<23:14, 232.49s/it]  [A100%|██████████| 8/8 [09:24<00:00, 70.50s/it] 
 22%|██▏       | 2/9 [22:39<1:17:44, 666.34s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [09:33<1:06:52, 573.25s/it][A
 38%|███▊      | 3/8 [09:33<12:23, 148.67s/it]  [A
 62%|██████▎   | 5/8 [09:36<03:38, 72.91s/it] [A100%|██████████| 8/8 [09:36<00:00, 72.00s/it]
 33%|███▎      | 3/9 [32:35<1:03:26, 634.40s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [10:13<1:11:36, 613.72s/it][A
 25%|██▌       | 2/8 [10:14<25:19, 253.33s/it]  [A
 50%|█████     | 4/8 [10:16<06:20, 95.20s/it] [A100%|██████████| 8/8 [10:16<00:00, 77.12s/it]
 44%|████▍     | 4/9 [43:12<52:55, 635.10s/it]  
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [10:56<1:16:37, 656.84s/it][A
 25%|██▌       | 2/8 [10:57<27:03, 270.56s/it]  [A
 38%|███▊      | 3/8 [10:57<12:16, 147.29s/it][A
 75%|███████▌  | 6/8 [10:58<01:39, 49.96s/it] [A100%|██████████| 8/8 [10:58<00:00, 82.29s/it]
 56%|█████▌    | 5/9 [54:30<43:23, 650.85s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [10:35<1:14:10, 635.82s/it][A
 75%|███████▌  | 6/8 [10:35<02:36, 78.11s/it]   [A100%|██████████| 8/8 [10:36<00:00, 79.62s/it]
 67%|██████▋   | 6/9 [1:05:21<32:31, 650.66s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [10:48<1:15:42, 648.87s/it][A
 50%|█████     | 4/8 [10:50<08:12, 123.08s/it]  [A
 88%|████████▊ | 7/8 [10:50<00:57, 57.19s/it] [A100%|██████████| 8/8 [10:50<00:00, 81.37s/it]
 78%|███████▊  | 7/9 [1:16:24<21:49, 654.81s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [11:18<1:19:06, 678.14s/it][A
 25%|██▌       | 2/8 [11:19<27:59, 279.94s/it]  [A
 38%|███▊      | 3/8 [11:20<12:42, 152.52s/it][A100%|██████████| 8/8 [11:20<00:00, 85.03s/it] 
 89%|████████▉ | 8/9 [1:27:52<11:05, 665.28s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [11:30<1:20:36, 690.99s/it][A
 62%|██████▎   | 5/8 [11:31<05:09, 103.09s/it]  [A100%|██████████| 8/8 [11:31<00:00, 86.48s/it] 
100%|██████████| 9/9 [1:39:37<00:00, 677.64s/it]100%|██████████| 9/9 [1:39:37<00:00, 664.12s/it]
Exception ignored in: <function Pool.__del__ at 0x2b624d058430>
Traceback (most recent call last):
  File "/home/n9455647/.conda/envs/conda_test/lib/python3.8/multiprocessing/pool.py", line 268, in __del__
  File "/home/n9455647/.conda/envs/conda_test/lib/python3.8/multiprocessing/queues.py", line 362, in put
AttributeError: 'NoneType' object has no attribute 'dumps'
