RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
  0%|          | 0/14 [00:00<?, ?it/s]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [01:30<10:30, 90.03s/it][A
 62%|██████▎   | 5/8 [01:30<00:40, 13.51s/it][A100%|██████████| 8/8 [01:30<00:00, 11.31s/it]
  7%|▋         | 1/14 [02:42<35:16, 162.84s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [02:05<14:40, 125.80s/it][A
 25%|██▌       | 2/8 [02:07<05:17, 52.97s/it] [A100%|██████████| 8/8 [02:07<00:00, 15.97s/it]
 14%|█▍        | 2/14 [06:01<36:49, 184.12s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [02:09<15:09, 129.98s/it][A
 38%|███▊      | 3/8 [02:15<02:58, 35.80s/it] [A100%|██████████| 8/8 [02:15<00:00, 16.96s/it]
 21%|██▏       | 3/14 [09:18<34:48, 189.87s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [02:10<15:12, 130.39s/it][A
 25%|██▌       | 2/8 [02:12<05:30, 55.12s/it] [A
 50%|█████     | 4/8 [02:12<01:22, 20.60s/it][A100%|██████████| 8/8 [02:12<00:00, 16.62s/it]
 29%|██▊       | 4/14 [12:28<31:38, 189.87s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [02:11<15:23, 131.91s/it][A
 88%|████████▊ | 7/8 [02:12<00:13, 13.90s/it] [A100%|██████████| 8/8 [02:12<00:00, 16.59s/it]
 36%|███▌      | 5/14 [15:34<28:14, 188.33s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [02:10<15:13, 130.55s/it][A
 25%|██▌       | 2/8 [02:12<05:28, 54.75s/it] [A
 38%|███▊      | 3/8 [02:12<02:29, 29.92s/it][A
 62%|██████▎   | 5/8 [02:12<00:39, 13.03s/it][A
100%|██████████| 8/8 [02:12<00:00,  5.92s/it][A100%|██████████| 8/8 [02:12<00:00, 16.62s/it]
 43%|████▎     | 6/14 [18:24<24:18, 182.32s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [02:01<14:09, 121.33s/it][A
 25%|██▌       | 2/8 [02:03<05:06, 51.16s/it] [A
 50%|█████     | 4/8 [02:03<01:16, 19.23s/it][A
 88%|████████▊ | 7/8 [02:05<00:08,  8.54s/it][A100%|██████████| 8/8 [02:05<00:00, 15.70s/it]
 50%|█████     | 7/14 [20:43<19:36, 168.09s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [02:06<14:45, 126.53s/it][A100%|██████████| 8/8 [02:06<00:00, 15.82s/it] 
 57%|█████▋    | 8/14 [22:58<15:45, 157.59s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [01:53<13:16, 113.84s/it][A
 25%|██▌       | 2/8 [02:07<05:29, 54.84s/it] [A
 38%|███▊      | 3/8 [02:08<02:31, 30.37s/it][A
 88%|████████▊ | 7/8 [02:12<00:09,  9.10s/it][A100%|██████████| 8/8 [02:12<00:00, 16.56s/it]
 64%|██████▍   | 9/14 [25:18<12:40, 152.11s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [02:02<14:14, 122.05s/it][A
 25%|██▌       | 2/8 [02:08<05:25, 54.19s/it] [A
 38%|███▊      | 3/8 [02:12<02:35, 31.18s/it][A
 88%|████████▊ | 7/8 [02:13<00:08,  8.73s/it][A100%|██████████| 8/8 [02:13<00:00, 16.63s/it]
 71%|███████▏  | 10/14 [27:40<09:56, 149.00s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [02:02<14:15, 122.25s/it][A
 88%|████████▊ | 7/8 [02:04<00:13, 13.04s/it] [A100%|██████████| 8/8 [02:04<00:00, 15.50s/it]
 79%|███████▊  | 11/14 [29:59<07:17, 145.76s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A  0%|          | 0/8 [01:57<?, ?it/s]
 79%|███████▊  | 11/14 [31:59<08:43, 174.47s/it]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/n9455647/.conda/envs/conda_test/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "el_white_box_fidelity.py", line 394, in test_fidelity
    exp_score, explanation_features = get_explanation_features(explainer, instance, cls, scaler, dataset_ref, classification, exp_iter, xai_method,
  File "el_white_box_fidelity.py", line 354, in get_explanation_features
    exp_score, feat_pos = get_lime_features(explainer, instance, cls, classification, exp_iter, feat_list, percentile)
  File "el_white_box_fidelity.py", line 221, in get_lime_features
    n = feat_list.index(feat_name)
ValueError: '-0.00' is not in list
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "el_white_box_fidelity.py", line 534, in <module>
    for result in tqdm(pool.imap(test_fidelity, [i for i in range(len(sample_instances))]), total = len(sample_instances)):
  File "/home/n9455647/.conda/envs/conda_test/lib/python3.8/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/n9455647/.conda/envs/conda_test/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
ValueError: '-0.00' is not in list
