RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
  0%|          | 0/1 [00:00<?, ?it/s]
  0%|          | 0/112 [00:00<?, ?it/s][A
  1%|          | 1/112 [78:32:38<8718:22:38, 282758.18s/it][A
  2%|▏         | 2/112 [85:52:56<4032:25:32, 131970.30s/it][A
 19%|█▉        | 21/112 [99:14:58<256:51:59, 10161.76s/it] [A
 42%|████▏     | 47/112 [100:19:38<66:21:27, 3675.19s/it] [A
 48%|████▊     | 54/112 [104:34:44<54:25:39, 3378.27s/it][A
 67%|██████▋   | 75/112 [104:56:37<19:00:53, 1850.10s/it][A
 68%|██████▊   | 76/112 [114:35:40<28:30:01, 2850.03s/it][A
 71%|███████   | 79/112 [114:58:03<23:35:12, 2573.11s/it][A100%|██████████| 112/112 [114:58:03<00:00, 3695.39s/it]  
100%|██████████| 1/1 [114:58:08<00:00, 413888.45s/it]100%|██████████| 1/1 [114:58:08<00:00, 413888.45s/it]
Exception ignored in: <function Pool.__del__ at 0x2aabd5693430>
Traceback (most recent call last):
  File "/home/n9455647/.conda/envs/conda_test/lib/python3.8/multiprocessing/pool.py", line 268, in __del__
  File "/home/n9455647/.conda/envs/conda_test/lib/python3.8/multiprocessing/queues.py", line 362, in put
AttributeError: 'NoneType' object has no attribute 'dumps'
