RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
  0%|          | 0/14 [00:00<?, ?it/s]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [00:57<06:39, 57.06s/it][A100%|██████████| 8/8 [00:57<00:00,  7.13s/it]
  7%|▋         | 1/14 [01:01<13:22, 61.70s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [01:04<07:31, 64.44s/it][A
 25%|██▌       | 2/8 [01:06<02:46, 27.67s/it][A
 38%|███▊      | 3/8 [01:08<01:19, 15.80s/it][A
 50%|█████     | 4/8 [01:12<00:45, 11.29s/it][A100%|██████████| 8/8 [01:12<00:00,  9.05s/it]
 14%|█▍        | 2/14 [02:21<14:29, 72.44s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [01:11<08:21, 71.71s/it][A
 25%|██▌       | 2/8 [01:13<03:02, 30.40s/it][A
 50%|█████     | 4/8 [01:15<00:48, 12.09s/it][A100%|██████████| 8/8 [01:15<00:00,  9.45s/it]
 21%|██▏       | 3/14 [03:40<13:51, 75.58s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [01:16<08:55, 76.54s/it][A
 25%|██▌       | 2/8 [01:17<03:11, 31.99s/it][A
 38%|███▊      | 3/8 [01:22<01:37, 19.58s/it][A100%|██████████| 8/8 [01:22<00:00, 10.27s/it]
 29%|██▊       | 4/14 [05:13<13:42, 82.25s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [01:18<09:11, 78.85s/it][A
 25%|██▌       | 2/8 [01:21<03:25, 34.20s/it][A
 38%|███▊      | 3/8 [01:24<01:38, 19.78s/it][A100%|██████████| 8/8 [01:24<00:00, 10.55s/it]
 36%|███▌      | 5/14 [06:45<12:51, 85.76s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [01:24<09:51, 84.56s/it][A
 50%|█████     | 4/8 [01:27<01:06, 16.75s/it][A100%|██████████| 8/8 [01:27<00:00, 10.92s/it]
 43%|████▎     | 6/14 [08:27<12:09, 91.21s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [01:29<10:24, 89.20s/it][A100%|██████████| 8/8 [01:29<00:00, 11.15s/it]
 50%|█████     | 7/14 [10:01<10:44, 92.09s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [01:31<10:38, 91.22s/it][A
 88%|████████▊ | 7/8 [01:32<00:09,  9.74s/it][A100%|██████████| 8/8 [01:32<00:00, 11.57s/it]
 57%|█████▋    | 8/14 [11:37<09:21, 93.53s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [01:33<10:57, 93.87s/it][A
 62%|██████▎   | 5/8 [01:34<00:42, 14.21s/it][A100%|██████████| 8/8 [01:34<00:00, 11.87s/it]
 64%|██████▍   | 9/14 [13:23<08:06, 97.28s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [01:32<10:49, 92.74s/it][A
 50%|█████     | 4/8 [01:33<01:10, 17.67s/it][A
 62%|██████▎   | 5/8 [01:33<00:38, 12.94s/it][A
 75%|███████▌  | 6/8 [01:34<00:18,  9.43s/it][A
100%|██████████| 8/8 [01:36<00:00,  5.60s/it][A100%|██████████| 8/8 [01:36<00:00, 12.03s/it]
 71%|███████▏  | 10/14 [15:14<06:46, 101.72s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [01:36<11:12, 96.01s/it][A
 38%|███▊      | 3/8 [01:39<02:10, 26.19s/it][A100%|██████████| 8/8 [01:39<00:00, 12.44s/it]
 79%|███████▊  | 11/14 [17:00<05:08, 102.87s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [01:39<11:36, 99.48s/it][A
 62%|██████▎   | 5/8 [01:40<00:45, 15.04s/it][A
 88%|████████▊ | 7/8 [01:42<00:09,  9.74s/it][A100%|██████████| 8/8 [01:42<00:00, 12.82s/it]
 86%|████████▌ | 12/14 [18:49<03:29, 104.82s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [01:41<11:50, 101.53s/it][A
 50%|█████     | 4/8 [01:43<01:19, 19.78s/it] [A100%|██████████| 8/8 [01:43<00:00, 12.96s/it]
 93%|█████████▎| 13/14 [20:37<01:45, 105.81s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [01:39<11:38, 99.84s/it][A
 25%|██▌       | 2/8 [01:43<04:18, 43.01s/it][A
 50%|█████     | 4/8 [01:43<01:04, 16.25s/it][A
 75%|███████▌  | 6/8 [01:44<00:17,  8.72s/it][A100%|██████████| 8/8 [01:44<00:00, 13.04s/it]
100%|██████████| 14/14 [22:24<00:00, 106.12s/it]100%|██████████| 14/14 [22:24<00:00, 96.04s/it] 
Exception ignored in: <function Pool.__del__ at 0x2b65fb6004c0>
Traceback (most recent call last):
  File "/home/n9455647/.conda/envs/conda_test/lib/python3.8/multiprocessing/pool.py", line 268, in __del__
  File "/home/n9455647/.conda/envs/conda_test/lib/python3.8/multiprocessing/queues.py", line 362, in put
AttributeError: 'NoneType' object has no attribute 'dumps'
