RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
  0%|          | 0/14 [00:00<?, ?it/s]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [00:22<02:35, 22.28s/it][A
 75%|███████▌  | 6/8 [00:22<00:05,  2.85s/it][A100%|██████████| 8/8 [00:22<00:00,  2.87s/it]
  7%|▋         | 1/14 [00:33<07:20, 33.90s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [00:44<05:12, 44.65s/it][A
 75%|███████▌  | 6/8 [00:45<00:11,  5.62s/it][A100%|██████████| 8/8 [00:45<00:00,  5.68s/it]
 14%|█▍        | 2/14 [01:26<08:57, 44.80s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [01:10<08:11, 70.22s/it][A
 50%|█████     | 4/8 [01:10<00:53, 13.38s/it][A
 88%|████████▊ | 7/8 [01:10<00:06,  6.26s/it][A100%|██████████| 8/8 [01:10<00:00,  8.87s/it]
 21%|██▏       | 3/14 [02:45<11:06, 60.56s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [01:34<11:00, 94.29s/it][A
 25%|██▌       | 2/8 [01:35<03:58, 39.68s/it][A
 75%|███████▌  | 6/8 [01:37<00:18,  9.39s/it][A100%|██████████| 8/8 [01:37<00:00, 12.15s/it]
 29%|██▊       | 4/14 [04:29<12:55, 77.54s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [01:58<13:47, 118.22s/it][A
 38%|███▊      | 3/8 [01:59<02:34, 30.96s/it] [A100%|██████████| 8/8 [01:59<00:00, 14.88s/it]
 36%|███▌      | 5/14 [06:35<14:16, 95.18s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [02:25<16:57, 145.41s/it][A
 38%|███▊      | 3/8 [02:25<03:08, 37.74s/it] [A
 62%|██████▎   | 5/8 [02:26<00:55, 18.47s/it][A100%|██████████| 8/8 [02:26<00:00, 18.26s/it]
 43%|████▎     | 6/14 [09:09<15:20, 115.01s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [02:50<19:52, 170.33s/it][A
 38%|███▊      | 3/8 [02:51<03:43, 44.68s/it] [A
 50%|█████     | 4/8 [02:52<01:57, 29.41s/it][A100%|██████████| 8/8 [02:52<00:00, 21.54s/it]
 50%|█████     | 7/14 [12:08<15:51, 135.89s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [03:18<23:08, 198.36s/it][A
 25%|██▌       | 2/8 [03:21<08:19, 83.24s/it] [A100%|██████████| 8/8 [03:21<00:00, 25.13s/it]
 57%|█████▋    | 8/14 [15:40<16:01, 160.26s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [03:42<25:59, 222.85s/it][A
 25%|██▌       | 2/8 [03:44<09:18, 93.01s/it] [A
 75%|███████▌  | 6/8 [03:45<00:42, 21.37s/it][A100%|██████████| 8/8 [03:45<00:00, 28.15s/it]
 64%|██████▍   | 9/14 [19:32<15:13, 182.75s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [04:08<28:57, 248.20s/it][A
 25%|██▌       | 2/8 [04:08<10:14, 102.34s/it][A
 50%|█████     | 4/8 [04:10<02:34, 38.70s/it] [A
 62%|██████▎   | 5/8 [04:11<01:21, 27.11s/it][A100%|██████████| 8/8 [04:11<00:00, 31.42s/it]
 71%|███████▏  | 10/14 [23:51<13:44, 206.15s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [04:40<32:42, 280.30s/it][A100%|██████████| 8/8 [04:40<00:00, 35.04s/it] 
 79%|███████▊  | 11/14 [28:45<11:39, 233.09s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [05:06<35:46, 306.59s/it][A
 75%|███████▌  | 6/8 [05:07<01:15, 37.74s/it] [A
100%|██████████| 8/8 [05:09<00:00, 25.49s/it][A100%|██████████| 8/8 [05:09<00:00, 38.65s/it]
 86%|████████▌ | 12/14 [34:02<08:37, 258.69s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [05:35<39:10, 335.77s/it][A100%|██████████| 8/8 [05:35<00:00, 41.97s/it] 
 93%|█████████▎| 13/14 [39:46<04:44, 284.36s/it]
  0%|          | 0/8 [00:00<?, ?it/s][A
 12%|█▎        | 1/8 [05:53<41:15, 353.58s/it][A
 25%|██▌       | 2/8 [05:56<14:43, 147.17s/it][A
 38%|███▊      | 3/8 [06:01<06:52, 82.40s/it] [A100%|██████████| 8/8 [06:01<00:00, 45.20s/it]
100%|██████████| 14/14 [45:56<00:00, 310.43s/it]100%|██████████| 14/14 [45:56<00:00, 196.91s/it]
Exception ignored in: <function Pool.__del__ at 0x2b93070a74c0>
Traceback (most recent call last):
  File "/home/n9455647/.conda/envs/conda_test/lib/python3.8/multiprocessing/pool.py", line 268, in __del__
  File "/home/n9455647/.conda/envs/conda_test/lib/python3.8/multiprocessing/queues.py", line 362, in put
AttributeError: 'NoneType' object has no attribute 'dumps'
